### ISSUE TITLE
message missing date header is read as today

### ISSUE THREAD

**Issue by eMBee** [sup-heliotrope/sup#247]
when a message is missing a Date: header then it is filed with the current date instead of using the timestamp in the "From " header.

**Comment by ralfebert** [comment]
Stumbled upon this: I had a mail message without a 'Date:' header in my old sent mailbox (Apple iCal seems to have sent a calendar invitation without a date header 2 years ago). sup v0.22.1 shows the date when it first encountered this message then - which is super-confusing because it made me think I just sent a calendar invitation for a 2 year old event to somebody.
