### ISSUE TITLE
Incorrect screen rendering after poll

### ISSUE THREAD

**Issue by madhat2r** [sup-heliotrope/sup#292]
After polling finds/adds new messages. The screen is improperly drawn. Must use <C-l> to redraw. 

The image below you will notice three of the same emails "Announce@DevExpress" these are in fact the same email, I just moved the cursor line after the poll to demonstrate what is happening. 

You will also notice the bottom of the screen at the status area is malformed.

![supdrawingerror](https://cloud.githubusercontent.com/assets/4122449/2750962/3038c1fc-c8a8-11e3-860b-d5609533f6c7.png)

And this picture is what it looks like after <C-l> redrawing:

![supdrawingerror_after_refresh](https://cloud.githubusercontent.com/assets/4122449/2750974/af232ea8-c8a8-11e3-8b8c-e09de2664a2b.png)

**Comment by dset0x** [comment]
I'm commenting here since this more accurately describes my problem than #490, the difference being that I have this issue when I receive a new message (not on every poll).

The issue is consistent and happens on every single new message. It persists even when I open a message, so I still have to `^L`.

##### Potentially relevant configuration:
* after-poll.rb
```ruby
if num_inbox > 0
    puts 7.chr
end
```
* before-poll.rb
```
say "Running mbsync..."
system "mbsync -a 2>&1 | awk '{ print strftime(), $0; fflush() }' >> ~/.sup/mbsync.log"
```

##### Other information:
OS: Gentoo x86_64
sup v0.22.1
[ruby20](https://packages.gentoo.org/packages/dev-lang/ruby) 2.0.0_p645 with USE-flags: `berkdb` `gdbm` `ipv6` `ncurses` `rdoc` `readline` `ssl`
[ncurses](https://packages.gentoo.org/packages/sys-libs/ncurses) 5.9-r99 with USE-flags: `abi_x86_32` `cxx` `gpm` `tinfo` `unicode`

**Comment by gauteh** [comment]
Using puts is likely to cause some troubles since ncurses is currently handling output. Could you try if the problem persists with both hooks disabled (run mbsync manually, then start poll).

**Comment by dset0x** [comment]
@gauteh 

That seems to have fixed it actually. I tried with and without the `mbsync` hook.

I took the advice of putting `puts` from the wiki. Is there perhaps an alternative to it?

**Comment by gauteh** [comment]
maybe the puts is ok.

try redirecting all output including stderr from mbsync somewhere.

Dimitrios Semitsoglou-Tsiapos writes on November 11, 2015 15:16:

**Comment by dset0x** [comment]
@gauteh `2>&1` should redirect both stdout and stderr, no?

**Comment by gauteh** [comment]
Dimitrios Semitsoglou-Tsiapos writes on November 11, 2015 15:48:
> @gauteh `2>&1` should redirect both stdout and stderr, no?

It should (since you are redirecting stdout), maybe you need one after
the awk command too?

**Comment by gauteh** [comment]
Gaute Hope writes on November 11, 2015 17:11:
> Dimitrios Semitsoglou-Tsiapos writes on November 11, 2015 15:48:
>> @gauteh `2>&1` should redirect both stdout and stderr, no?
> 
> It should (since you are redirecting stdout), maybe you need one after
> the awk command too?

Also, you could try replacing the .say with a .flash
