### ISSUE TITLE
Mac OS X 13.2.0 ncursesw-ruby build issue: cannot find libncurses

### ISSUE THREAD

**Issue by 0xErnie** [sup-heliotrope/sup#317]
Hello,

I got a Mac at work, most of the time I was using Linux. Installing sup does not seem to be that easy.

I followed https://github.com/sup-heliotrope/sup/wiki/Mac-OSX , installed rvm, the older ruby and a newer version of ncurses, but `gem install sup` seems to ignore it.

ncureses is linked via `brew link nurses`

```
$ ncurses5-config --version
5.9.20110404
```

It seems to be quite similar to #69.

```
$ ruby extconf.rb
checking for unistd.h... yes
checking for locale.h... yes
checking for ncursesw/curses.h... no
checking for ncurses.h... yes
checking for wmove() in -lncursesw... no
checking for wmove() in -lpdcurses... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/akauerz/.rvm/rubies/ruby-1.9.3-p547/bin/ruby
    --with-ncurseswlib
    --without-ncurseswlib
    --with-pdcurseslib
    --without-pdcurseslib
extconf.rb:48:in `<main>': ncurses library not found (RuntimeError)
```

**Comment by vsbuffalo** [comment]
I have this same issue. Frustrating. Any updates? Tried brewing ncurses, forcing links, etc. etc. with no resolution.

**Comment by gauteh** [comment]
You also need to make sure that any leftovers from previous ncurses-ruby are gone.

**Comment by danmichaelo** [comment]
I tried filing an issue at https://github.com/rlane/ncursesw-ruby/issues/5 , since I guess this is more of an issue with ncursesw than sup.

For some reason, `ruby extconf.rb` didn't look in `/usr/local/include/`, so `gem link ncurses -f` didn't make any difference. By adding `dir_config('ncurses')` to `extconf.rb` I could add `--with-ncurses-dir=/usr/local/Cellar/ncurses/5.9` to the install command, and finally get `checking for ncursesw/curses.h... yes`

… but the `wmove()` tests still failed :sob:

**Comment by gauteh** [comment]
@danmichaelo: We use our own version of ncursesw, could you check if anything here: https://github.com/sup-heliotrope/ncursesw-ruby/issues/17 helps?

**Comment by danmichaelo** [comment]
Thanks @gauteh ! Turns out I was using the OS X-bundled Ruby 2.0.0. By installing 2.2.0 from `brew install ruby`, it worked! I still had to add `dir_config('ncurses')` to`/usr/local/lib/ruby/gems/2.2.0/gems/ncursesw-1.4.9\extconf.rb` so I could run `ruby extconf.rb -- --with-ncurses-dir=/usr/local/opt/ncurses/` (but that could probably be avoided by doing `brew link ncurses -f` for those who are ok with that)

**Comment by focs** [comment]
Thanks @danmichaelo ! that worked for me.

**Comment by JuPlutonic** [comment]
```sh
brew link -f ruby ncurses gcc
CXX=./bin/g++ ruby extconf.rb -- --with-opt-include=./include/ncursesw/ --with-opt-lib=./ --without-ncurses-dir

gem build ncursesw.gemspec && gem install ncursesw-1.4.10.gem
```
