### ISSUE TITLE
Follow GH Ruby styleguide

### ISSUE THREAD

**Issue by ZJvandeWeg** [sup-heliotrope/sup#402]
When reading through the source you'll notice alot of different style used. Im under the impression that nobody reads HACKING and therefor propose to switch to the [Github Ruby Styleguide](https://github.com/styleguide/ruby) for all future commit as it seems more 'standard' than HACKING.

**Comment by maxmeyer** [comment]
Why not introducing https://github.com/bbatsov/rubocop to the project? You can add this to the rake task running the test suite. This will check/ensure the Community Ruby Styleguide https://github.com/bbatsov/ruby-style-guide.

**Comment by ZJvandeWeg** [comment]
Could rubocops output automatically be posted on PR's as Travis now does?

**Comment by maxmeyer** [comment]
There's no need for that from my point of view. You could use [their rake-task](https://github.com/bbatsov/rubocop#rake-integration) and make your test-task to depend on that:

```ruby
task test: %w(test:rubocop test:minitest)
```

Then add something like this to `.travis.yml`:

```ruby
[...]
script: rake test
[...]
```

On every push to github `rake test` is run. And because it depends on `rake test:rubocop`, rubocop runs before the minitest-testsuite is run. And it fails with an understandable error message which exactly tell what you need to fix. 

BTW You want something like this in your `.rubocop.yml`.

```yaml
AllCops:
  Exclude:
    - 'tmp/**/*'
  DisplayCopNames: true
```

**Comment by ZJvandeWeg** [comment]
Thanks. Im interested in what @gauteh thinks about this?

**Comment by gauteh** [comment]
That would probably be good, but it also requires us to go through the old source and fix it.

**Comment by ZJvandeWeg** [comment]
Ill have time on my hands in the near future. I can pick this up, though I would like some help if possible.

**Comment by rumpelsepp** [comment]
> Could rubocops output automatically be posted on PR's as Travis now does?

Hound does: https://houndci.com/

**Comment by danc86** [comment]
At this point in Sup's life I don't think there's any point in doing a mass reformatting of its source code.

I'm slowly developing a fondness for its idiosyncratic "poetry mode" code style anyway. :-)
