### ISSUE TITLE
Option to sign/import/trust Key

### ISSUE THREAD

**Issue by binaryplease** [sup-heliotrope/sup#461]
When recieving a message which is signed, if the key is not yet known I can't find a option to trust the sender.

It would be nice to have a way to inspect and verify the key and if trustworthy import it for future use.

**Comment by rakoo** [comment]
The gpg key already has its own chunk. Here's an anonymized example:

```
  Signature made Fri 09 Aug 2015 02:19:56 CEST using RSA key ID 1234AB6789
  Good signature from "First Last (preferred key) <first@last.org>"
                  aka "First-Alt Last <first-alt@last.org>"
  WARNING: This key is not certified with a trusted signature!
  There is no indication that the signature belongs to the owner
  Full fingerprint is: 1234:5678:ABCD:EFEF:87654:4321:FEFE:DCBA:2490:8137
```

It is true that this chunk doesn't show the sub keys, and I believe it's ok because it's not the goal of the chunk to show all subkeys, but rather the key that was used for this message.

I can see 2 quick hacks for achieving what you want, using the pipe command:

- A program that parses the mail's key and shows the full details
- A program that parses the mail's key and verifies the key

(Of course it can be the same program called with different arguments)

The problem would be the distribution of such a program, because it's not a true hook as we know them. Moreover I'm kind of wary about having a ui on top of gpg that might misrepresent some information by error.

**Comment by gauteh** [comment]
I think this is out of the scope of sup's job. #178 is kind of related. I'm going to close this for now.
