### ISSUE TITLE
Failing to start sup bin

### ISSUE THREAD

**Issue by hahcho** [sup-heliotrope/sup#508]
I have installed the sup gem but I am having this issue when I try running `sup`

```
/home/mario/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- fiddle (LoadError)
        from /home/mario/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/mario/.rvm/gems/ruby-2.1.5/gems/sup-0.22.1/lib/sup/util/locale_fiddler.rb:5:in `<top (required)>'
        from /home/mario/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/mario/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/mario/.rvm/gems/ruby-2.1.5/gems/sup-0.22.1/bin/sup:9:in `<top (required)>'
        from /home/mario/.rvm/gems/ruby-2.1.5/bin/sup:23:in `load'
        from /home/mario/.rvm/gems/ruby-2.1.5/bin/sup:23:in `<main>'
        from /home/mario/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
        from /home/mario/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

I researched a little and installed `libffi` and `ffi` gem but this did not help. I am out of ideas if somebody can help me. I am running `ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]`.

**Comment by danc86** [comment]
The `fiddle` module is supposed to be part of the Ruby standard library since 1.9.2 so I am not quite sure how you got a Ruby interpreter without it. Maybe it's optional and only enabled if Ruby is built when it can find headers for libffi? I'm not too sure. If that is the case, you could probably fix this by ensuring you have `libffi-devel` or whatever your distro's equivalent package is installed, and then having rvm rebuild the interpreter.
