### ISSUE TITLE
Login with Outlook / Office 365 Mail

### ISSUE THREAD

**Issue by iqlal** [sup-heliotrope/sup#605]
Hi i just found this project. This project is really cool !!!

Can i login as Outlook / Office 365 Mail, maybe using IMAP / POP3 ???

Thanks

**Comment by danc86** [comment]
Sup itself doesn't know anything about IMAP. It only works with maildir (or mbox) files locally. There are plenty of other programs you can use to synchronize a remote IMAP mailbox to a local maildir for sup. Offlineimap is a commonly used one. There's some notes [here in the wiki](https://github.com/sup-heliotrope/sup/wiki#configuring-the-way-email-is-retrieved).

I don't have any experience with Outlook365. Typically these cloud services are difficult because they require unusual/nonstandard authentication mechanisms like OAuth2. But I can find plenty of search results online for how to configure offlineimap for Outlook365 so it's probably possible.

If you find out more, please feel free to add some notes here, or we can add some links to more info in the Sup wiki.

**Comment by iqlal** [comment]
@danc86 Thanks for answer :)
