### ISSUE TITLE
Missing `mime/types` dependency in Debian Bullseye

### ISSUE THREAD

**Issue by Tomaz-Vieira** [sup-heliotrope/sup#611]
Running `sup-mail` in Debian Bullseye after installing via `apt install sup-mail` raises this error:

```
Ignoring executable-hooks-1.6.1 because its extensions are not built. Try: gem pristine executable-hooks --version 1.6.1
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
Traceback (most recent call last):
	8: from /usr/bin/sup-mail:8:in `<main>'
	7: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	6: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	5: from /usr/lib/ruby/vendor_ruby/sup/util/ncurses.rb:2:in `<top (required)>'
	4: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	3: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	2: from /usr/lib/ruby/vendor_ruby/sup/util.rb:5:in `<top (required)>'
	1: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- mime/types (LoadError)
```

I thought maybe installing `ruby-mime-types` and `ruby-mime-types-data` would solve it, but it wasn't the case

**Comment by Tomaz-Vieira** [comment]
I tried in a clean(er) debootstrapped container and it actually works there... It might be something on my machine

**Comment by danc86** [comment]
Sup declares a dependency on the `mime-types` gem in `sup.gemspec` so I don't think there is any bug on the Sup side. I'm not too familiar with Debian packaging, I see that all the expected gems are declared as `Build-Depends` but not `Depends`:
https://salsa.debian.org/ruby-team/sup-mail/-/blob/master/debian/control
so that might be the problem?

Another common issue would be if you have accidentally done `sudo gem install sup` at some point and it has overwritten some parts of the regular `sup-mail` Debian package with its own copy that is looking in the wrong Ruby path, something like that.

If you can reproduce the issue I'd suggest to file a Debian bug. Please feel free to reopen this one if you find something wrong in Sup itself.
