### ISSUE TITLE
Sup on M1, M2 Mac / Apple Silicon

### ISSUE THREAD

**Issue by hmltn-2** [sup-heliotrope/sup#613]
I am pretty sure the gem installation does not work on Mac M1 / Apple Silicon.

I might try to fork it and see if I can build it from source and if I need to modify anything.

If anyone can please let me know more information about this I'd appreciate it.

Thanks.

**Comment by danc86** [comment]
What error are you seeing?

Sup and all its dependencies does build and work fine on aarch64 Linux (I use it on aarch64 Linux every day) but of course Mac OS is different in many ways. If you can paste an error I can try to guess what might be going wrong, although I do not use or own a Mac, nor do I know much about the operating system.

**Comment by barracuda156** [comment]
@danc86 Fails for me on macOS:
```
_rb_undef_method, referenced from:\n      _Init__xapian in xapian_wrap.o\n  _rb_unexpected_type, referenced from:\n      _Init__xapian in xapian_wrap.o\nclang: error: linker command failed with exit code 1 (use -v to see invocation)\nmake[3]: *** [_xapian.la] Error 1\nmake[2]: *** [all] Error 2\nmake[1]: *** [all-recursive] Error 1\nmake: *** [all] Error 2
```
[rb33-sup_Sonoma.log](https://github.com/sup-heliotrope/sup/files/14405682/rb33-sup_Sonoma.log)

**Comment by barracuda156** [comment]
@danc86 Thank you, I will try.

P. S. On a side note: looks like I haven’t built `xapian-core` on PowerPC earlier (there was no need for it until now), and I cannot test it right now (temporarily no access to hardware); do you have an idea if that could work or something there relies on newer SDKs? Port installation [history for the past year](https://ports.macports.org/port/xapian-core/stats/?days=365&days_ago=0) shows 10.11+, though it does not necessarily mean that no one installed it on earlier systems (statistics won’t be sent to Macports by default, plus older macOS require a custom Macports set-up for it to work due to outdated system `curl`).

**Comment by barracuda156** [comment]
@danc86 A quick update, xapian-bindings install fine on their own on Sonoma (turned out Macports has them already, I just added support for Ruby 3.3).

I need to figure out how to configure sup gem to use those, since by default they are not picked.

**Comment by barracuda156** [comment]
@danc86 Could you help with adding a configure option to use external Xapian bindings? That is the easiest solution, perhaps, rather than trying to fix broken gems (`xapian-full-alaveteli` gem also fails to build, so it looks like the bug is with Xapian upstream, but it is fixed in Macports, so we can just use that).

**Comment by danc86** [comment]
We have this hack, which tries to conditionally install the `xapian-ruby` gem unless running on OpenBSD: https://github.com/sup-heliotrope/sup/blob/develop/ext/mkrf_conf_xapian.rb#L17

I'm not sure if there is a nicer way to have "optional" gem dependencies...

**Comment by barracuda156** [comment]
> We have this hack, which tries to conditionally install the `xapian-ruby` gem unless running on OpenBSD: https://github.com/sup-heliotrope/sup/blob/develop/ext/mkrf_conf_xapian.rb#L17
> 
> I'm not sure if there is a nicer way to have "optional" gem dependencies...

@danc86 Yes, I have seen that and referred to above. So I guess, we want to skip building `xapian-ruby` for Darwin as well, not only for OpenBSD. (Though there should be a way to do it conditionally on a user choice instead of hardcoding on the system, which is prone to failure.)

**Comment by danc86** [comment]
It's getting a bit off-topic for this issue now, but that look like an issue with Ruby 3.2 which I fixed in this commit: https://github.com/sup-heliotrope/sup/commit/d2a2a0d7544237a29bf932773cc85e9050bd9c26 (not released yet). If you're running from source, please try the `develop` branch, it has a few fixes for recent Rubies. We are probably overdue for a new release.

**Comment by barracuda156** [comment]
@danc86 Thank you, will try it.

If we could think of some reasonable way to optionally use pre-built Xapian bindings on macOS (or perhaps any system) instead of force-building those (which is broken), without patching the sources from our side, it would be very helpful. I think it will also be a general improvement, not just a fix specifically for MacPorts users. At least for all systems using package managers (FreeBSD, NetBSD etc.).

**Comment by barracuda156** [comment]
@danc86 Yes, `develop` branch works!
![sup](https://github.com/sup-heliotrope/sup/assets/92015510/b6be6eac-672d-4996-8de0-02ef91beaef1)

(Please consider some solution to allow external Xapian bindings before releasing the new version.)

**Comment by danc86** [comment]
I did a bit of searching to understand if there is any better solution these days for optional gem dependencies, or conditional dependencies, or platform-specific dependencies... and it seems like there is none, apart from the `extconf.rb` hack which sup already uses.

In commit 492091ad4d544da7fce650b70347a151f5edb053 I changed the condition to check for a `SUP_SKIP_XAPIAN_GEM_INSTALL` environment variable, instead of conditionalising on OpenBSD.

**Comment by barracuda156** [comment]
@danc86 Thank you!

**Comment by danc86** [comment]
Sup 1.2 is released.
